# Generated by Django 3.2.5 on 2021-11-29 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='owner',
        ),
    ]
